# Generated by Django 2.1.12 on 2020-06-18 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('genres', models.CharField(max_length=50)),
                ('original_title', models.CharField(max_length=100)),
                ('original_language', models.CharField(max_length=10)),
                ('overview', models.CharField(max_length=500)),
                ('adult', models.BooleanField()),
                ('budget', models.CharField(max_length=20)),
                ('poster_path', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('runtime', models.CharField(max_length=5)),
                ('vote_average', models.CharField(max_length=5)),
                ('video', models.CharField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('star', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
